import './globals.css';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import { Navbar } from './component/navbar';
import { Footer } from './component/footer';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <main>
        {children}
        </main>
        <Footer/>
        </body>
    </html>
  )
}
